// TechTreeData.h - the tech tree, compiled into the game.
//
// GENERATED by TechTreeEditor (tools/TechTreeEditor). Open this file in the
// editor to change the tree. Hand edits work too if you keep the format
// (see include/TechData.h) - the editor will read them back.
#pragma once

// The text is split into chunks to stay under compiler string-length limits.
inline constexpr const char* kTechTreeData[] = {
R"TECHTREE(# IncraVegetable tech tree. Made with TechTreeEditor (tools/TechTreeEditor).
# Format: see include/TechData.h
version 1

crop lettuce
  name Lettuce
  value 1
  grow 1
  pick 1
  weight 45
  tier 0
  look lettuce
end

crop carrot
  name Carrot
  value 4
  grow 1.6
  pick 1.25
  weight 35
  tier 1
  look carrot
end

crop pumpkin
  name Pumpkin
  value 15
  grow 2.6
  pick 1.6
  weight 20
  tier 2
  look pumpkin
end

crop turnip
  name Turnip
  value 38
  grow 3.4
  pick 1.9
  weight 15
  tier 3
  look round
end

crop chilli
  name Chilli
  value 60
  grow 5.2
  pick 3.2
  weight 15
  tier 4
  look round
end

crop broccoli
  name Broccoli
  value 70
  grow 6
  pick 3.5
  weight 15
  tier 5
  look round
end

crop corn
  name Corn
  value 80
  grow 6.8
  pick 3.8
  weight 15
  tier 6
  look round
end

crop eggplant
  name Eggplant
  value 90
  grow 7.6
  pick 4.1
  weight 15
  tier 7
  look round
end

tech barn
  name The Barn
  desc Unlocks the barn.
  max 1
  cost 4
  growth 1
  pos 0 0
end

tech patch
  name Bigger Patch 1
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 5
  growth 1
  pos -0 1.179
  requires barn 1
  effect patchSize add 1
end

tech daylength
  name Longer Days 1
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 5
  growth 1
  pos 0.817 -0.589
  requires barn 1
  effect dayLength add 2
end

tech seeds
  name More Seeds 1
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 6
  growth 1
  pos -0.817 -0.589
  requires barn 1
  effect maxCrops add 1
end

tech pickspeed
  name Quick Hands 1
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 6
  growth 1
  pos -0.817 0.589
  requires barn 1
  effect pickTime multiply 0.82
end

tech patch_2
  name Bigger Patch 2
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 7
  growth 1
  pos -1.633 1.179
  icon patch
  requires pickspeed 1
  effect patchSize add 1
end

tech daylength_2
  name Longer Days 2
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 7
  growth 1
  pos -2.45 0.589
  icon daylength
  requires patch_2 1
  effect dayLength add 2
end

tech growspeed
  name Fertile Soil 1
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 9
  growth 1
  pos 0.817 0.589
  requires barn 1
  effect growTime multiply 0.88
end

tech seeds_2
  name More Seeds 2
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 9
  growth 1
  pos 1.633 1.179
  icon seeds
  requires growspeed 1
  effect maxCrops add 1
end

tech daylength_3
  name Longer Days 3
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 9
  growth 1
  pos 1.633 2.357
  icon daylength
  requires seeds_2 1
  effect dayLength add 2
end

tech patch_3
  name Bigger Patch 3
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 10
  growth 1
  pos 2.45 1.768
  icon patch
  requires seeds_2 1
  effect patchSize add 1
end

tech seeds_3
  name More Seeds 3
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 10
  growth 1
  pos -2.45 1.768
  icon seeds
  requires patch_2 1
  effect maxCrops add 2
end

tech daylength_4
  name Longer Days 4
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 10
  growth 1
  pos -3.266 2.357
  icon daylength
  requires seeds_3 1
  effect dayLength add 2
end

tech patch_4
  name Bigger Patch 4
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 12
  growth 1
  pos -4.083 2.946
  icon patch
  requires daylength_4 1
  effect patchSize add 1
end

tech pickspeed_2
  name Quick Hands 2
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 12
  growth 1
  pos 2.45 0.589
  icon pickspeed
  requires seeds_2 1
  effect pickTime multiply 0.82
end

tech seeds_4
  name More Seeds 4
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 14
  growth 1
  pos -4.899 3.536
  icon seeds
  requires patch_4 1
  effect maxCrops add 2
end

tech carrots
  name Carrots
  desc Unlocks carrots. They grow slower but sell for 4 coins each.
  max 1
  cost 14
  growth 1
  pos -0 2.357
  requires patch 1
  effect cropTier atleast 1
end

tech daylength_5
  name Longer Days 5
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 30
  growth 1
  pos -0 3.536
  icon daylength
  requires carrots 1
  effect dayLength add 2
end

tech patch_5
  name Bigger Patch 5
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 33
  growth 1
  pos -0 4.714
  icon patch
  requires daylength_5 1
  effect patchSize add 1
end

tech growspeed_2
  name Fertile Soil 2
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 34
  growth 1
  pos -0.817 2.946
  icon growspeed
  requires carrots 1
  effect growTime multiply 0.88
end

tech value
  name Prize Produce 1
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 34
  growth 1
  pos 0 -1.179
  requires barn 1
  effect valueMult add 0.25
end

tech seeds_5
  name More Seeds 5
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 43
  growth 1
  pos 0 -2.357
  icon seeds
  requires value 1
  effect maxCrops add 2
end

tech daylength_6
  name Longer Days 6
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 44
  growth 1
  pos 0 -3.536
  icon daylength
  requires seeds_5 1
  effect dayLength add 2
end

tech patch_6
  name Bigger Patch 6
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 48
  growth 1
  pos 0.817 -2.946
  icon patch
  requires seeds_5 1
  effect patchSize add 1
end

tech value_2
  name Prize Produce 2
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 48
  growth 1
  pos 0.817 2.946
  icon value
  requires carrots 1
  effect valueMult add 0.25
end

tech seeds_6
  name More Seeds 6
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 59
  growth 1
  pos -0.817 5.304
  icon seeds
  requires patch_5 1
  effect maxCrops add 3
end

tech daylength_7
  name Longer Days 7
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 59
  growth 1
  pos 3.266 2.357
  icon daylength
  requires patch_3 1
  effect dayLength add 2
end

tech pickspeed_3
  name Quick Hands 3
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 65
  growth 1
  pos -0.817 -2.946
  icon pickspeed
  requires seeds_5 1
  effect pickTime multiply 0.82
end

tech patch_7
  name Bigger Patch 7
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 75
  growth 1
  pos 0 -4.714
  icon patch
  requires daylength_6 1
  effect patchSize add 1
end

tech daylength_8
  name Longer Days 8
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 76
  growth 1
  pos -1.633 5.893
  icon daylength
  requires seeds_6 1
  effect dayLength add 2
end

tech seeds_7
  name More Seeds 7
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 82
  growth 1
  pos 4.083 1.768
  icon seeds
  requires daylength_7 1
  effect maxCrops add 4
end

tech patch_8
  name Bigger Patch 8
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 83
  growth 1
  pos 4.899 1.179
  icon patch
  requires seeds_7 1
  effect patchSize add 1
end

tech growspeed_3
)TECHTREE",
R"TECHTREE(  name Fertile Soil 3
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 84
  growth 1
  pos -1.633 2.357
  icon growspeed
  requires patch_2 1
  effect growTime multiply 0.88
end

tech autopick
  name Helping Hand
  desc Sometimes picking a crop also picks a ripe one next to it: 10% chance, 1 crop, within 1.5 plant widths.
  max 1
  cost 85
  growth 1
  pos 1.633 -1.179
  requires daylength 1
  effect autoPickChance add 10
  effect autoPickCount add 1
  effect autoPickRadius add 1.5
end

tech daylength_9
  name Longer Days 9
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 94
  growth 1
  pos 2.45 -1.768
  icon daylength
  requires autopick 1
  effect dayLength add 2
end

tech headstart
  name Head Start 1
  desc Crops keep growing overnight. Part of the patch is already ripe when the day begins.
  max 1
  cost 100
  growth 1
  pos 2.45 -0.589
  requires autopick 1
  effect headStart add 0.2
end

tech value_3
  name Prize Produce 3
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 110
  growth 1
  pos 1.633 -2.357
  icon value
  requires autopick 1
  effect valueMult add 0.25
end

tech seeds_8
  name More Seeds 8
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 130
  growth 1
  pos 3.266 -2.357
  icon seeds
  requires daylength_9 1
  effect maxCrops add 5
end

tech patch_9
  name Bigger Patch 9
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 140
  growth 1
  pos 4.083 -1.768
  icon patch
  requires seeds_8 1
  effect patchSize add 1
end

tech autopickchance
  name Lucky Streak 1
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 140
  growth 1
  pos 4.083 -2.946
  requires seeds_8 1
  effect autoPickChance add 5
end

tech reach
  name Wide Reach 1
  desc Long arms. Pick every ripe vegetable inside a circle around the mouse.
  max 1
  cost 150
  growth 1
  pos 0.817 -5.304
  requires patch_7 1
  effect reach add 1
end

tech daylength_10
  name Longer Days 10
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 200
  growth 1
  pos 1.633 -5.893
  icon daylength
  requires reach 1
  effect dayLength add 2
end

tech pickspeed_4
  name Quick Hands 4
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 220
  growth 1
  pos 0.817 5.304
  icon pickspeed
  requires patch_5 1
  effect pickTime multiply 0.82
end

tech farmhand
  name Farmhand
  desc Hire a farmer who walks the patch picking ripe crops for you. Farmers pick the nearest ripe crop no one else is going for.
  max 1
  cost 250
  growth 1
  pos -1.633 -1.179
  requires seeds 1
  effect farmers add 1
end

tech seeds_9
  name More Seeds 9
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 300
  growth 1
  pos -0.817 -5.304
  icon seeds
  requires patch_7 1
  effect maxCrops add 6
end

tech patch_10
  name Bigger Patch 10
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 300
  growth 1
  pos -2.45 -1.768
  icon patch
  requires farmhand 1
  effect patchSize add 1
end

tech daylength_11
  name Longer Days 11
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 310
  growth 1
  pos -1.633 -2.357
  icon daylength
  requires farmhand 1
  effect dayLength add 2
end

tech seeds_10
  name More Seeds 10
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 330
  growth 1
  pos -3.266 -2.357
  icon seeds
  requires patch_10 1
  effect maxCrops add 7
end

tech autopickchance_2
  name Lucky Streak 2
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 340
  growth 1
  pos 4.899 -1.179
  icon autopickchance
  requires patch_9 1
  effect autoPickChance add 5
end

tech patch_11
  name Bigger Patch 11
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 350
  growth 1
  pos 4.899 -3.536
  icon patch
  requires autopickchance 1
  effect patchSize add 1
end

tech daylength_12
  name Longer Days 12
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 350
  growth 1
  pos -4.083 -2.946
  icon daylength
  requires seeds_10 1
  effect dayLength add 2
end

tech growspeed_4
  name Fertile Soil 4
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 370
  growth 1
  pos -2.45 -0.589
  icon growspeed
  requires farmhand 1
  effect growTime multiply 0.88
end

tech pumpkins
  name Pumpkins
  desc Unlocks pumpkins. Slow to grow and hard to pick, but worth 15 coins each.
  max 1
  cost 370
  growth 1
  pos -0 5.893
  requires patch_5 1
  effect cropTier atleast 2
end

tech value_4
  name Prize Produce 4
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 750
  growth 1
  pos -0 7.071
  icon value
  requires pumpkins 1
  effect valueMult add 0.25
end

tech headstart_2
  name Head Start 2
  desc Crops keep growing overnight. Part of the patch is already ripe when the day begins.
  max 1
  cost 870
  growth 1
  pos -0 8.25
  icon headstart
  requires value_4 1
  effect headStart add 0.2
end

tech farmerspeed
  name Comfy Boots 1
  desc Farmers walk faster.
  max 1
  cost 940
  growth 1
  pos -4.083 -1.768
  requires seeds_10 1
  effect farmerSpeed add 0.4
end

tech seeds_11
  name More Seeds 11
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 960
  growth 1
  pos -0 9.429
  icon seeds
  requires headstart_2 1
  effect maxCrops add 10
end

tech daylength_13
  name Longer Days 13
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 1000
  growth 1
  pos -1.633 -5.893
  icon daylength
  requires seeds_9 1
  effect dayLength add 2
end

tech pickspeed_5
  name Quick Hands 5
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 1100
  growth 1
  pos -3.266 -3.536
  icon pickspeed
  requires seeds_10 1
  effect pickTime multiply 0.82
end

tech patch_12
  name Bigger Patch 12
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 1200
  growth 1
  pos -4.899 -1.179
  icon patch
  requires farmerspeed 1
  effect patchSize add 1
end

tech autopickchance_3
  name Lucky Streak 3
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 1200
  growth 1
  pos 5.716 -4.125
  icon autopickchance
  requires patch_11 1
  effect autoPickChance add 5
end

tech autopickradius
  name Spreading Roots 1
  desc Helping Hand reaches further: +0.5 plant widths.
  max 1
  cost 1200
  growth 1
  pos 3.266 -3.536
  requires seeds_8 1
  effect autoPickRadius add 0.5
end

tech seeds_12
  name More Seeds 12
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 1200
  growth 1
  pos 5.716 -2.946
  icon seeds
  requires patch_11 1
  effect maxCrops add 11
end

tech daylength_14
  name Longer Days 14
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 1300
  growth 1
  pos 3.266 -4.714
  icon daylength
  requires autopickradius 1
  effect dayLength add 2
end

tech patch_13
  name Bigger Patch 13
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 1300
  growth 1
  pos -4.899 -3.536
  icon patch
  requires daylength_12 1
  effect patchSize add 1
end

tech reach_2
  name Wide Reach 2
  desc Long arms. Pick every ripe vegetable inside a circle around the mouse.
  max 1
  cost 1400
  growth 1
  pos 3.266 3.536
  icon reach
  requires daylength_7 1
  effect reach add 1
end

tech autopickradius_2
  name Spreading Roots 2
  desc Helping Hand reaches further: +0.5 plant widths.
  max 1
  cost 2600
  growth 1
  pos 4.899 -4.714
)TECHTREE",
R"TECHTREE(  icon autopickradius
  requires patch_11 1
  effect autoPickRadius add 0.5
end

tech farmcrew
  name Farm Crew 1
  desc Hire one more farmer to walk the patch picking ripe crops for you.
  max 1
  cost 2600
  growth 1
  pos 4.083 2.946
  requires daylength_7 1
  effect farmers add 1
end

tech farmerspeed_2
  name Comfy Boots 2
  desc Farmers walk faster.
  max 1
  cost 2800
  growth 1
  pos -3.266 -4.714
  icon farmerspeed
  requires pickspeed_5 1
  effect farmerSpeed add 0.4
end

tech value_5
  name Prize Produce 5
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 2800
  growth 1
  pos -3.266 3.536
  icon value
  requires daylength_4 1
  effect valueMult add 0.25
end

tech daylength_15
  name Longer Days 15
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 3200
  growth 1
  pos 1.633 5.893
  icon daylength
  requires pickspeed_4 1
  effect dayLength add 2
end

tech seeds_13
  name More Seeds 13
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 3400
  growth 1
  pos -3.266 4.714
  icon seeds
  requires value_5 1
  effect maxCrops add 15
end

tech patch_14
  name Bigger Patch 14
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 3500
  growth 1
  pos 3.266 4.714
  icon patch
  requires reach_2 1
  effect patchSize add 1
end

tech growspeed_5
  name Fertile Soil 5
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 3500
  growth 1
  pos 0 -5.893
  icon growspeed
  requires patch_7 1
  effect growTime multiply 0.88
end

tech autopickchance_4
  name Lucky Streak 4
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 3500
  growth 1
  pos 4.899 -5.893
  icon autopickchance
  requires autopickradius_2 1
  effect autoPickChance add 5
end

tech pickspeed_6
  name Quick Hands 6
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 3600
  growth 1
  pos -4.083 1.768
  icon pickspeed
  requires daylength_4 1
  effect pickTime multiply 0.82
end

tech daylength_16
  name Longer Days 16
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 4000
  growth 1
  pos -5.716 2.946
  icon daylength
  requires seeds_4 1
  effect dayLength add 2
end

tech seeds_14
  name More Seeds 14
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 4200
  growth 1
  pos 0 -7.071
  icon seeds
  requires growspeed_5 1
  effect maxCrops add 18
end

tech patch_15
  name Bigger Patch 15
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 4300
  growth 1
  pos -4.899 1.179
  icon patch
  requires pickspeed_6 1
  effect patchSize add 1
end

tech headstart_3
  name Head Start 3
  desc Crops keep growing overnight. Part of the patch is already ripe when the day begins.
  max 1
  cost 4300
  growth 1
  pos 5 3.5
  icon headstart
  requires farmcrew 1
  effect headStart add 0.2
end

tech farmerspeed_3
  name Comfy Boots 3
  desc Farmers walk faster.
  max 1
  cost 4600
  growth 1
  pos -5.716 -2.946
  icon farmerspeed
  requires patch_13 1
  effect farmerSpeed add 0.4
end

tech daylength_17
  name Longer Days 17
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 4600
  growth 1
  pos 4.899 4.714
  icon daylength
  requires headstart_3 1
  effect dayLength add 2
end

tech seeds_15
  name More Seeds 15
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 4800
  growth 1
  pos -5.716 -4.125
  icon seeds
  requires patch_13 1
  effect maxCrops add 23
end

tech patch_16
  name Bigger Patch 16
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 5100
  growth 1
  pos 0.817 -7.661
  icon patch
  requires seeds_14 1
  effect patchSize add 1
end

tech value_6
  name Prize Produce 6
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 5100
  growth 1
  pos 6.5 4.5
  icon value
  requires headstart_3 1
  effect valueMult add 0.25
end

tech autopickradius_3
  name Spreading Roots 3
  desc Helping Hand reaches further: +0.5 plant widths.
  max 1
  cost 5700
  growth 1
  pos 6.532 -2.357
  icon autopickradius
  requires seeds_12 1
  effect autoPickRadius add 0.5
end

tech autopickchance_5
  name Lucky Streak 5
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 5800
  growth 1
  pos 7.349 -1.768
  icon autopickchance
  requires autopickradius_3 1
  effect autoPickChance add 5
end

tech daylength_18
  name Longer Days 18
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 5800
  growth 1
  pos -6.532 -2.357
  icon daylength
  requires farmerspeed_3 1
  effect dayLength add 2
end

tech farmcrew_2
  name Farm Crew 2
  desc Hire one more farmer to walk the patch picking ripe crops for you.
  max 1
  cost 6100
  growth 1
  pos -4.899 4.714
  icon farmcrew
  requires seeds_4 1
  effect farmers add 1
end

tech seeds_16
  name More Seeds 16
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 6500
  growth 1
  pos 0.817 7.661
  icon seeds
  requires value_4 1
  effect maxCrops add 28
end

tech patch_17
  name Bigger Patch 17
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 6800
  growth 1
  pos -0.817 7.661
  icon patch
  requires value_4 1
  effect patchSize add 1
end

tech growspeed_6
  name Fertile Soil 6
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 6800
  growth 1
  pos 9.5 -7
  icon growspeed
  requires eggplant 1
  effect growTime multiply 0.88
end

tech farmerspeed_4
  name Comfy Boots 4
  desc Farmers walk faster.
  max 1
  cost 6900
  growth 1
  pos -6.532 -4.714
  icon farmerspeed
  requires seeds_15 1
  effect farmerSpeed add 0.4
end

tech farmerpick
  name Sharp Shears 1
  desc Farmers pick 15% faster.
  max 1
  cost 6900
  growth 1
  pos -4.899 -4.714
  requires patch_13 1
  effect farmerPickTime multiply 0.85
end

tech pickspeed_7
  name Quick Hands 7
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 7100
  growth 1
  pos 0 -8.25
  icon pickspeed
  requires seeds_14 1
  effect pickTime multiply 0.82
end

tech farmerpick_2
  name Sharp Shears 2
  desc Farmers pick 15% faster.
  max 1
  cost 7700
  growth 1
  pos -7.349 -1.768
  icon farmerpick
  requires daylength_18 1
  effect farmerPickTime multiply 0.85
end

tech farmerpick_3
  name Sharp Shears 3
  desc Farmers pick 15% faster.
  max 1
  cost 8300
  growth 1
  pos -6.532 -5.893
  icon farmerpick
  requires farmerspeed_4 1
  effect farmerPickTime multiply 0.85
end

tech daylength_19
  name Longer Days 19
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 8100
  growth 1
  pos -0.817 -7.661
  icon daylength
  requires seeds_14 1
  effect dayLength add 2
end

tech farmerpick_4
  name Sharp Shears 4
  desc Farmers pick 15% faster.
  max 1
  cost 9000
  growth 1
  pos -7.349 -4.125
  icon farmerpick
  requires farmerspeed_4 1
  effect farmerPickTime multiply 0.85
end

tech patch_18
  name Bigger Patch 18
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 8700
  growth 1
  pos 5.716 2.946
  icon patch
  requires headstart_3 1
  effect patchSize add 1
end

tech seeds_17
  name More Seeds 17
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 8800
  growth 1
  pos 9.5 6.5
  icon seeds
  requires chilli 1
  effect maxCrops add 36
end

tech autopickchance_6
  name Lucky Streak 6
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 9200
  growth 1
  pos 10.316999 -7.5899997
  icon autopickchance
  requires growspeed_6 1
)TECHTREE",
R"TECHTREE(  effect autoPickChance add 5
end

tech autopickcount
  name Bumper Bunch 1
  desc Helping Hand picks one more nearby crop.
  max 1
  cost 9300
  growth 1
  pos 4.899 -7.071
  requires autopickchance_4 1
  effect autoPickCount add 1
end

tech autopickcount_2
  name Bumper Bunch 2
  desc Helping Hand picks one more nearby crop.
  max 1
  cost 10000
  growth 1
  pos 9.5 -8.179
  icon autopickcount
  requires growspeed_6 1
  effect autoPickCount add 1
end

tech autopickcount_3
  name Bumper Bunch 3
  desc Helping Hand picks one more nearby crop.
  max 1
  cost 11000
  growth 1
  pos 11.132999 -8.179
  icon autopickcount
  requires autopickchance_6 1
  effect autoPickCount add 1
end

tech daylength_20
  name Longer Days 20
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 11000
  growth 1
  pos -4.899 5.893
  icon daylength
  requires farmcrew_2 1
  effect dayLength add 2
end

tech value_7
  name Prize Produce 7
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 12000
  growth 1
  pos -4.899 -5.893
  icon value
  requires farmerpick 1
  effect valueMult add 0.25
end

tech patch_19
  name Bigger Patch 19
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 13000
  growth 1
  pos 1.633 8.25
  icon patch
  requires seeds_16 1
  effect patchSize add 1
end

tech turnip
  name Turnips
  desc Unlocks turnips. The slowest crop of all, but worth 38 coins each.
  max 1
  cost 13000
  growth 1
  pos 0 12.5
  icon crop_turnip
  requires seeds_11 1
  effect cropTier atleast 3
end

tech headstart_4
  name Head Start 4
  desc Crops keep growing overnight. Part of the patch is already ripe when the day begins.
  max 1
  cost 24000
  growth 1
  pos -6 4.5
  icon headstart
  requires seeds_4 1
  effect headStart add 0.2
end

tech autopickradius_4
  name Spreading Roots 4
  desc Helping Hand reaches further: +0.5 plant widths.
  max 1
  cost 25000
  growth 1
  pos 10.316999 -6.411
  icon autopickradius
  requires growspeed_6 1
  effect autoPickRadius add 0.5
end

tech farmerspeed_5
  name Comfy Boots 5
  desc Farmers walk faster.
  max 1
  cost 26000
  growth 1
  pos -4.899 -7.071
  icon farmerspeed
  requires value_7 1
  effect farmerSpeed add 0.4
end

tech seeds_18
  name More Seeds 18
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 26000
  growth 1
  pos 6.532 2.357
  icon seeds
  requires patch_18 1
  effect maxCrops add 44
end

tech daylength_21
  name Longer Days 21
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 27000
  growth 1
  pos -1.633 8.25
  icon daylength
  requires patch_17 1
  effect dayLength add 2
end

tech farmerpick_5
  name Sharp Shears 5
  desc Farmers pick 15% faster.
  max 1
  cost 28000
  growth 1
  pos -9.5 -7.5
  icon farmerpick
  requires corn 1
  effect farmerPickTime multiply 0.85
end

tech pickspeed_8
  name Quick Hands 8
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 29000
  growth 1
  pos 4.899 5.893
  icon pickspeed
  requires daylength_17 1
  effect pickTime multiply 0.82
end

tech autopickchance_7
  name Lucky Streak 7
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 31000
  growth 1
  pos 9.5 -9.357
  icon autopickchance
  requires autopickcount_2 1
  effect autoPickChance add 5
end

tech patch_20
  name Bigger Patch 20
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 32000
  growth 1
  pos 0 -9.429
  icon patch
  requires pickspeed_7 1
  effect patchSize add 1
end

tech growspeed_7
  name Fertile Soil 7
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 32000
  growth 1
  pos -9 6.5
  icon growspeed
  requires broccoli 1
  effect growTime multiply 0.88
end

tech reach_3
  name Wide Reach 3
  desc Long arms. Pick every ripe vegetable inside a circle around the mouse.
  max 1
  cost 32000
  growth 1
  pos -6.532 2.357
  icon reach
  requires daylength_16 1
  effect reach add 1
end

tech farmcrew_3
  name Farm Crew 3
  desc Hire one more farmer to walk the patch picking ripe crops for you.
  max 1
  cost 45000
  growth 1
  pos 1.633 -8.25
  icon farmcrew
  requires patch_16 1
  effect farmers add 1
end

tech daylength_22
  name Longer Days 22
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 47000
  growth 1
  pos 9.5 7.679
  icon daylength
  requires seeds_17 1
  effect dayLength add 2
end

tech seeds_19
  name More Seeds 19
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 48000
  growth 1
  pos 0 -10.607
  icon seeds
  requires patch_20 1
  effect maxCrops add 56
end

tech daylength_23
  name Longer Days 23
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 51000
  growth 1
  pos 0.817 -10.018
  icon daylength
  requires patch_20 1
  effect dayLength add 2
end

tech patch_21
  name Bigger Patch 21
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 52000
  growth 1
  pos -9 7.679
  icon patch
  requires growspeed_7 1
  effect patchSize add 1
end

tech value_8
  name Prize Produce 8
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 53000
  growth 1
  pos -1.633 -8.25
  icon value
  requires daylength_19 1
  effect valueMult add 0.25
end

tech farmerspeed_6
  name Comfy Boots 6
  desc Farmers walk faster.
  max 1
  cost 58000
  growth 1
  pos -10.316 -8.089001
  icon farmerspeed
  requires farmerpick_5 1
  effect farmerSpeed add 0.4
end

tech seeds_20
  name More Seeds 20
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 58000
  growth 1
  pos -9.816999 7.0899997
  icon seeds
  requires growspeed_7 1
  effect maxCrops add 69
end

tech autopickcount_4
  name Bumper Bunch 4
  desc Helping Hand picks one more nearby crop.
  max 1
  cost 61000
  growth 1
  pos 11.132999 -5.8219995
  icon autopickcount
  requires autopickradius_4 1
  effect autoPickCount add 1
end

tech farmerpick_6
  name Sharp Shears 6
  desc Farmers pick 15% faster.
  max 1
  cost 64000
  growth 1
  pos -11.133 -7.5
  icon farmerpick
  requires farmerspeed_6 1
  effect farmerPickTime multiply 0.85
end

tech autopickchance_8
  name Lucky Streak 8
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 65000
  growth 1
  pos 11.950001 -5.232
  icon autopickchance
  requires autopickcount_4 1
  effect autoPickChance add 5
end

tech daylength_24
  name Longer Days 24
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 67000
  growth 1
  pos 0.817 10.018
  icon daylength
  requires seeds_11 1
  effect dayLength add 2
end

tech patch_22
  name Bigger Patch 22
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 69000
  growth 1
  pos -0.817 10.018
  icon patch
  requires seeds_11 1
  effect patchSize add 1
end

tech autopickradius_5
  name Spreading Roots 5
  desc Helping Hand reaches further: +0.5 plant widths.
  max 1
  cost 69000
  growth 1
  pos 11.950001 -8.768
  icon autopickradius
  requires autopickcount_3 1
  effect autoPickRadius add 0.5
end

tech seeds_21
  name More Seeds 21
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 70000
  growth 1
  pos 1.633 -10.607
  icon seeds
  requires daylength_23 1
  effect maxCrops add 87
end

tech pickspeed_9
  name Quick Hands 9
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 73000
  growth 1
  pos 1.633 10.607
  icon pickspeed
  requires daylength_24 1
  effect pickTime multiply 0.82
end

tech daylength_25
  name Longer Days 25
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 78000
)TECHTREE",
R"TECHTREE(  growth 1
  pos -9.816999 5.911
  icon daylength
  requires growspeed_7 1
  effect dayLength add 2
end

tech patch_23
  name Bigger Patch 23
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 81000
  growth 1
  pos 10.316999 7.0899997
  icon patch
  requires seeds_17 1
  effect patchSize add 1
end

tech growspeed_8
  name Fertile Soil 8
  desc Richer compost: vegetables grow 12% faster.
  max 1
  cost 81000
  growth 1
  pos -0.817 -10.018
  icon growspeed
  requires patch_20 1
  effect growTime multiply 0.88
end

tech headstart_5
  name Head Start 5
  desc Crops keep growing overnight. Part of the patch is already ripe when the day begins.
  max 1
  cost 81000
  growth 1
  pos -1.633 -10.607
  icon headstart
  requires growspeed_8 1
  effect headStart add 0.2
end

tech farmerspeed_7
  name Comfy Boots 7
  desc Farmers walk faster.
  max 1
  cost 86000
  growth 1
  pos -6.532 -7.071
  icon farmerspeed
  requires farmerpick_3 1
  effect farmerSpeed add 0.4
end

tech seeds_22
  name More Seeds 22
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 87000
  growth 1
  pos -9 8.857
  icon seeds
  requires patch_21 1
  effect maxCrops add 108
end

tech autopickchance_9
  name Lucky Streak 9
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 93000
  growth 1
  pos 12.766001 -9.357
  icon autopickchance
  requires autopickradius_5 1
  effect autoPickChance add 5
end

tech value_9
  name Prize Produce 9
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 95000
  growth 1
  pos 9.5 8.857
  icon value
  requires daylength_22 1
  effect valueMult add 0.25
end

tech farmcrew_4
  name Farm Crew 4
  desc Hire one more farmer to walk the patch picking ripe crops for you.
  max 1
  cost 100000
  growth 1
  pos 0 13.786
  icon farmcrew
  requires turnip 1
  effect farmers add 1
end

tech farmerpick_7
  name Sharp Shears 7
  desc Farmers pick 15% faster.
  max 1
  cost 110000
  growth 1
  pos -11.133 -8.6779995
  icon farmerpick
  requires farmerspeed_6 1
  effect farmerPickTime multiply 0.85
end

tech daylength_26
  name Longer Days 26
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 110000
  growth 1
  pos 11.132999 7.679
  icon daylength
  requires patch_23 1
  effect dayLength add 2
end

tech patch_24
  name Bigger Patch 24
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 110000
  growth 1
  pos -10.632999 5.3219995
  icon patch
  requires daylength_25 1
  effect patchSize add 1
end

tech seeds_23
  name More Seeds 23
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 110000
  growth 1
  pos -0.817 14.375
  icon seeds
  requires farmcrew_4 1
  effect maxCrops add 136
end

tech daylength_27
  name Longer Days 27
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 120000
  growth 1
  pos -10.632999 7.679
  icon daylength
  requires seeds_20 1
  effect dayLength add 2
end

tech pickspeed_10
  name Quick Hands 10
  desc Practice makes perfect: pick vegetables 18% faster.
  max 1
  cost 120000
  growth 1
  pos 10.316999 5.911
  icon pickspeed
  requires seeds_17 1
  effect pickTime multiply 0.82
end

tech patch_25
  name Bigger Patch 25
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 130000
  growth 1
  pos 11.132999 5.3219995
  icon patch
  requires pickspeed_10 1
  effect patchSize add 1
end

tech autopickcount_5
  name Bumper Bunch 5
  desc Helping Hand picks one more nearby crop.
  max 1
  cost 130000
  growth 1
  pos 9.5 -10.5
  icon autopickcount
  requires autopickchance_7 1
  effect autoPickCount add 1
end

tech autopickradius_6
  name Spreading Roots 6
  desc Helping Hand reaches further: +0.5 plant widths.
  max 1
  cost 140000
  growth 1
  pos 11.132999 -9.357
  icon autopickradius
  requires autopickcount_3 1
  effect autoPickRadius add 0.5
end

tech farmerspeed_8
  name Comfy Boots 8
  desc Farmers walk faster.
  max 1
  cost 140000
  growth 1
  pos -8.165 -3.536
  icon farmerspeed
  requires farmerpick_4 1
  effect farmerSpeed add 0.4
end

tech autopickchance_10
  name Lucky Streak 10
  desc Helping Hand happens more often: +5% chance.
  max 1
  cost 140000
  growth 1
  pos 11.950001 -7.5899997
  icon autopickchance
  requires autopickcount_3 1
  effect autoPickChance add 5
end

tech seeds_24
  name More Seeds 24
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 140000
  growth 1
  pos 11.132999 8.857
  icon seeds
  requires daylength_26 1
  effect maxCrops add 169
end

tech daylength_28
  name Longer Days 28
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 150000
  growth 1
  pos 0 -11.786
  icon daylength
  requires seeds_19 1
  effect dayLength add 2
end

tech farmerpick_8
  name Sharp Shears 8
  desc Farmers pick 15% faster.
  max 1
  cost 150000
  growth 1
  pos -10.316 -9.267
  icon farmerpick
  requires farmerspeed_6 1
  effect farmerPickTime multiply 0.85
end

tech patch_26
  name Bigger Patch 26
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 150000
  growth 1
  pos 0.817 -12.375
  icon patch
  requires daylength_28 1
  effect patchSize add 1
end

tech value_10
  name Prize Produce 10
  desc Bigger, shinier vegetables: every vegetable sells for a little more.
  max 1
  cost 160000
  growth 1
  pos -10.632999 8.857
  icon value
  requires daylength_27 1
  effect valueMult add 0.25
end

tech daylength_29
  name Longer Days 29
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 170000
  growth 1
  pos -1.633 10.607
  icon daylength
  requires patch_22 1
  effect dayLength add 2
end

tech seeds_25
  name More Seeds 25
  desc Sow more seeds: about 25% more vegetables grow at once, up to the room in your patch.
  max 1
  cost 170000
  growth 1
  pos -0.817 -12.375
  icon seeds
  requires daylength_28 1
  effect maxCrops add 212
end

tech patch_27
  name Bigger Patch 27
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 170000
  growth 1
  pos 0.817 14.375
  icon patch
  requires farmcrew_4 1
  effect patchSize add 1
end

tech daylength_30
  name Longer Days 30
  desc Wake up a little earlier: 2 more seconds of picking every day.
  max 1
  cost 180000
  growth 1
  pos 0 14.964
  icon daylength
  requires farmcrew_4 1
  effect dayLength add 2
end

tech patch_28
  name Bigger Patch 28
  desc Dig out a bigger patch: one more row and column of room for vegetables (up to 30 x 30).
  max 1
  cost 180000
  growth 1
  pos 11.950001 7.0899997
  icon patch
  requires daylength_26 1
  effect patchSize add 1
end

tech chilli
  name Chilli
  desc Unlocks Chilli. Sells for 60 coins each.
  max 1
  cost 100000
  growth 1
  pos 8 5.5
  icon crop_chilli
  requires value_6 1
  effect cropTier atleast 4
end

tech broccoli
  name Broccoli
  desc Unlocks Broccoli. Sells for 70 coins each.
  max 1
  cost 250000
  growth 1
  pos -7.5 5.5
  icon crop_broccoli
  requires headstart_4 1
  effect cropTier atleast 5
end

tech corn
  name Corn
  desc Unlocks Corn. Sells for 80 coins each.
  max 1
  cost 15000
  growth 1
  pos -8 -6
  icon crop_corn
  requires farmerspeed_4 1
  effect cropTier atleast 6
end

tech eggplant
  name Eggplant
  desc Unlocks Eggplant. Sells for 90 coins each.
  max 1
  cost 9000
  growth 1
  pos 7.5 -5.5
  icon crop_eggplant
  requires autopickchance_3 1
  effect cropTier atleast 7
end

)TECHTREE",
    nullptr,
};
