// TechTreeData.h - the tech tree, compiled into the game.
//
// GENERATED by TechTreeEditor (tools/TechTreeEditor). Open this file in the
// editor to change the tree. Hand edits work too if you keep the format
// (see include/TechData.h) - the editor will read them back.
#pragma once

// The text is split into chunks to stay under compiler string-length limits.
inline constexpr const char* kTechTreeData[] = {
R"TECHTREE(# IncraVegetable tech tree. Made with TechTreeEditor (tools/TechTreeEditor).
# Format: see include/TechData.h
version 1

tech patch
  name Bigger Patch
  desc Dig out a bigger patch with room for more vegetables. Each level adds a row and a column (up to 30 x 30).
  max 28
  cost 10
  growth 1.45
  pos 0 0
  effect patchSize add 1
end

tech seeds
  name More Seeds
  desc Sow more seeds. About 25% more vegetables grow at once per level, up to the room in your patch.
  max 25
  cost 6
  growth 1.5
  pos 2 0
  effect maxCrops multiply 1.25
end

tech daylength
  name Longer Days
  desc Wake up a little earlier. Each level adds 2 seconds to every day.
  max 30
  cost 6
  growth 1.28
  pos -1 0
  effect dayLength add 2
end

tech pickspeed
  name Quick Hands
  desc Practice makes perfect. Pick vegetables 18% faster per level.
  max 10
  cost 8
  growth 1.7
  pos 1 0
  effect pickTime multiply 0.82
end

tech headstart
  name Head Start
  desc Crops keep growing overnight. Part of the patch is already ripe when the day begins.
  max 5
  cost 60
  growth 2
  pos -1 1
  requires daylength 5
  effect headStart add 0.2
end

tech growspeed
  name Fertile Soil
  desc Richer compost. Vegetables grow 12% faster per level.
  max 8
  cost 25
  growth 1.8
  pos 0 1
  requires patch 1
  effect growTime multiply 0.88
end

tech value
  name Prize Produce
  desc Bigger, shinier vegetables. Every vegetable sells for 25% more per level.
  max 10
  cost 30
  growth 1.75
  pos 1 1
  requires pickspeed 1
  effect valueMult percent 25
end

tech reach
  name Wide Reach
  desc Long arms. Pick every ripe vegetable inside a circle around the mouse.
  max 3
  cost 150
  growth 3.5
  pos 2 1
  requires pickspeed 3
  effect reach add 1
end

tech carrots
  name Carrots
  desc Unlocks carrots. They grow slower but sell for 4 coins each.
  max 1
  cost 180
  growth 1
  pos 0 2
  requires growspeed 2
  effect cropTier atleast 1
end

tech pumpkins
  name Pumpkins
  desc Unlocks pumpkins. Slow to grow and hard to pick, but worth 15 coins each.
  max 1
  cost 1500
  growth 1
  pos 0.5 3
  requires carrots 1
  requires value 3
  effect cropTier atleast 2
end

tech autopick
  name Helping Hand
  desc Sometimes picking a crop also picks a ripe one next to it: 10% chance, 1 crop, within 1.5 plant widths.
  max 1
  cost 200
  growth 1
  pos 2.16 2
  requires reach 1
  effect autoPickChance add 10
  effect autoPickCount add 1
  effect autoPickRadius add 1.5
end

tech autopickchance
  name Lucky Streak
  desc Helping Hand happens more often: +5% chance per level.
  max 10
  cost 150
  growth 1.7
  pos 1.3 2
  requires autopick 1
  effect autoPickChance add 5
end

tech autopickcount
  name Bumper Bunch
  desc Helping Hand picks one more nearby crop per level.
  max 5
  cost 250
  growth 2.2
  pos 1.37 3
  requires autopick 1
  effect autoPickCount add 1
end

tech autopickradius
  name Spreading Roots
  desc Helping Hand reaches further: +0.5 plant widths per level.
  max 6
  cost 180
  growth 1.9
  pos 2.24 3
  requires autopick 1
  effect autoPickRadius add 0.5
end

tech farmhand
  name Farmhand
  desc Hire a farmer who walks the patch picking ripe crops for you. Farmers pick the nearest ripe crop no one else is going for.
  max 1
  cost 400
  growth 1
  pos -1 2
  requires growspeed 1
  effect farmers add 1
end

tech farmcrew
  name Farm Crew
  desc Hire another farmer per level.
  max 4
  cost 1200
  growth 2.4
  pos -1.5 3
  requires farmhand 1
  effect farmers add 1
end

tech farmerspeed
  name Comfy Boots
  desc Farmers walk 20% faster per level.
  max 8
  cost 300
  growth 1.8
  pos -0.5 3
  requires farmhand 1
  effect farmerSpeed percent 20
end

tech farmerpick
  name Sharp Shears
  desc Farmers pick 15% faster per level.
  max 8
  cost 350
  growth 1.85
  pos -1 4
  requires farmhand 1
  effect farmerPickTime multiply 0.85
end

)TECHTREE",
    nullptr,
};
